"""Platform connector routes (WordPress + Shopify).

WordPress: the user pastes the API key generated by the RankPilot plugin; we
call the plugin health-check and only store the (encrypted) key if it passes.

Shopify: a standard Admin API OAuth install. The authenticated `install`
endpoint returns the authorize URL; Shopify then redirects the browser to our
public `callback`, which verifies the request, exchanges the code for an
access token, stores it, and bounces the browser back to the app.
"""

from __future__ import annotations

import uuid
from urllib.parse import urlencode

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import RedirectResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.deps import ensure_project_access, get_current_user
from app.core.config import settings
from app.db.base import get_db
from app.models.user import User
from app.schemas.connectors import (
    CredentialsRead,
    ShopifyInstallRequest,
    ShopifyInstallResponse,
    WordPressConnectRequest,
)
from app.services import connector_service, shopify_service, wordpress_service
from app.services.shopify_service import ShopifyError

router = APIRouter()


# --- Status / disconnect ---------------------------------------------------


@router.get("", response_model=CredentialsRead | None)
async def get_connection(
    project_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> CredentialsRead | None:
    """Return the project's current connection, or null if none."""
    await ensure_project_access(project_id, current_user, db)
    cred = await connector_service.get_credentials(db, project_id)
    return cred  # type: ignore[return-value]  # serialized via CredentialsRead


@router.delete("", status_code=status.HTTP_204_NO_CONTENT)
async def disconnect(
    project_id: uuid.UUID,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    """Disconnect the project's platform and delete stored credentials."""
    project = await ensure_project_access(
        project_id, current_user, db, min_role="editor"
    )
    cred = await connector_service.get_credentials(db, project_id)
    if cred is not None:
        await db.delete(cred)
        project.platform = "custom"
        await db.commit()


# --- WordPress -------------------------------------------------------------


@router.post("/wordpress/connect", response_model=CredentialsRead)
async def connect_wordpress(
    payload: WordPressConnectRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> CredentialsRead:
    """Test the WordPress plugin connection and store credentials if valid."""
    await ensure_project_access(
        payload.project_id, current_user, db, min_role="editor"
    )

    health = await wordpress_service.check_connection(
        payload.site_url, payload.api_key
    )
    if not health.ok:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail=health.detail
        )

    cred = await connector_service.upsert_credentials(
        db,
        project_id=payload.project_id,
        platform="wordpress",
        secret=payload.api_key,
        site_url=health.site_url,
    )
    return cred  # type: ignore[return-value]


# --- Shopify ---------------------------------------------------------------


@router.post("/shopify/install", response_model=ShopifyInstallResponse)
async def shopify_install(
    payload: ShopifyInstallRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
) -> ShopifyInstallResponse:
    """Return the Shopify OAuth authorize URL for the browser to redirect to."""
    await ensure_project_access(
        payload.project_id, current_user, db, min_role="editor"
    )
    try:
        url = shopify_service.build_install(payload.project_id, payload.shop)
    except ShopifyError as exc:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc)
        ) from exc
    return ShopifyInstallResponse(authorize_url=url)


@router.get("/shopify/callback")
async def shopify_callback(
    request: Request,
    db: AsyncSession = Depends(get_db),
) -> RedirectResponse:
    """OAuth redirect target: verify, exchange the code, store the token.

    Unauthenticated (Shopify calls it directly); trust is established by the
    HMAC signature and our signed ``state``. Always bounces the browser back
    to the app's Connect page with a status.
    """
    params = dict(request.query_params)
    redirect_base = f"{settings.FRONTEND_URL.rstrip('/')}/dashboard/connect"

    def _bounce(**query: str) -> RedirectResponse:
        return RedirectResponse(
            url=f"{redirect_base}?{urlencode({'platform': 'shopify', **query})}",
            status_code=status.HTTP_302_FOUND,
        )

    try:
        callback = shopify_service.verify_callback(params)
        code = params.get("code")
        if not code:
            raise ShopifyError("Missing authorization code.")
        token = await shopify_service.exchange_code(callback.shop, code)
        await connector_service.upsert_credentials(
            db,
            project_id=callback.project_id,
            platform="shopify",
            secret=token,
            site_url=callback.shop,
        )
    except ShopifyError as exc:
        return _bounce(status="error", message=str(exc))

    return _bounce(status="connected", shop=callback.shop)
