"""Pydantic schemas for the platform connector system (WordPress + Shopify).

Mirrors the TypeScript types in ``packages/shared`` and the ``api.ts`` client.
The stored secret (WordPress key / Shopify token) is **never** serialized —
``CredentialsRead`` intentionally omits it.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

Platform = Literal["wordpress", "shopify", "custom"]
ConnectionStatus = Literal["connected", "error", "disconnected"]


class CredentialsRead(BaseModel):
    """A stored connection, safe to return (no secret)."""

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    project_id: uuid.UUID
    platform: Platform
    site_url: str | None = None
    status: ConnectionStatus
    connected_at: datetime | None = None
    created_at: datetime


# --- WordPress -------------------------------------------------------------


class WordPressConnectRequest(BaseModel):
    project_id: uuid.UUID
    site_url: str = Field(..., min_length=1, max_length=2048)
    # The API key generated by the RankPilot WordPress plugin.
    api_key: str = Field(..., min_length=1, max_length=512)


# --- Shopify ---------------------------------------------------------------


class ShopifyInstallRequest(BaseModel):
    project_id: uuid.UUID
    # The shop's myshopify domain, e.g. "my-store.myshopify.com" (or just
    # "my-store" — the service normalizes it).
    shop: str = Field(..., min_length=1, max_length=253)


class ShopifyInstallResponse(BaseModel):
    """The Shopify OAuth authorize URL the browser should be sent to."""

    authorize_url: str
